var edges = [
    {
        "source": "OLTP",
        "target": "TiDB"
    }, {
        source: '商业智能',
        target: '决策层'
    }, {
        source: '商业智能',
        target: '提供服务的方法'
    }, {
        source: '提供服务的方法',
        target: '分析报表'
    }, {
        source: '提供服务的方法',
        target: '数据湖'
    }, {
        source: '提供服务的方法',
        target: '数据平台'
    }, {
        source: '商业智能',
        target: '使用对象'
    }, {
        source: '使用对象',
        target: '数据开发者'
    }, {
        source: '使用对象',
        target: '数据技术人员'
    }, {
        source: '使用对象',
        target: '数据分析师'
    }, {
        source: '商业智能',
        target: '商业智能产出物'
    }, {
        source: '商业智能产出物',
        target: '数据集'
    }, {
        source: '商业智能产出物',
        target: 'Data Set'
    }, {
        source: '商业智能产出物',
        target: 'Database as a Service'
    }, {
        source: '商业智能产出物',
        target: '使用对象'
    }, {
        source: '数据中台',
        target: '数据中台用户'
    }, {
        source: '数据中台用户',
        target: '数据用户'
    }, {
        source: '数据中台用户',
        target: '数据消费者'
    }, {
        source: '数据中台用户',
        target: '业务系统'
    }, {
        source: '数据中台',
        target: '数据中台产品'
    }, {
        source: '数据中台用户',
        target: '数据中台产品'
    }, {
        source: '数据中台产品',
        target: 'Data API'
    }, {
        source: '数据中台产品',
        target: '数据服务'
    }, {
        source: 'Data Market',
        target: '数据仓库'
    }, {
        source: '阿里中台',
        target: 'One Data'
    }, {
        source: '阿里中台',
        target: 'One Entity'
    }, {
        source: '阿里中台',
        target: 'One Service'
    }, {
        source: 'RTP',
        target: 'oRTP'
    }, {
        source: 'RTP',
        target: 'JRTP'
    }, {
        source: '数据处理分类',
        target: 'OLTP'
    }, {
        source: '数据处理分类',
        target: 'OLAP'
    }, {
        source: 'OLAP',
        target: '数据仓库'
    }, {
        source: 'DDD',
        target: 'Axon'
    }, {
        source: 'WebGL',
        target: 'JavaScript'
    }, {
        source: 'WebGL',
        target: 'HTML5'
    }, {
        source: 'WebGL',
        target: 'OpenGL'
    }, {
        source: 'OLAP',
        target: 'ROLAP'
    }, {
        source: 'OLAP',
        target: 'MOLAP'
    }, {
        source: 'OLAP',
        target: 'HOLAP'
    }, {
        source: '阿里',
        target: '阿里中台'
    }, {
        source: '阿里',
        target: 'DRDS'
    }, {
        source: 'facebook',
        target: 'Presto'
    }, {
        source: 'ROLAP',
        target: 'mondrian'
    }, {
        source: 'ROLAP',
        target: 'Presto'
    }, {
        source: 'ROLAP',
        target: 'DRDS'
    }, {
        source: 'MOLAP',
        target: 'Kylin'
    }, {
        source: 'MOLAP',
        target: 'Lylin'
    }, {
        source: 'MOLAP',
        target: 'pinot'
    }, {
        source: 'MOLAP',
        target: 'Druid'
    }, {
        source: 'apache',
        target: 'Kylin'
    }, {
        source: 'ebay',
        target: 'Lylin'
    }, {
        source: 'linkedin',
        target: 'pinot'
    }, {
        source: 'MPP',
        target: 'Presto'
    }, {
        source: 'MPP',
        target: 'Impala'
    }, {
        source: 'MPP',
        target: 'SparkSQL'
    }, {
        source: 'MPP',
        target: 'Drill'
    }, {
        source: '预计算系统',
        target: 'Druid'
    }, {
        source: '预计算系统',
        target: 'Kylin'
    }, {
        source: '搜索引擎系统',
        target: 'Elasticsearch'
    }, {
        source: 'OLAP',
        target: 'OLAP引擎'
    }, {
        source: 'OLAP引擎',
        target: 'MPP'
    }, {
        source: 'OLAP引擎',
        target: '预计算系统'
    }, {
        source: 'OLAP引擎',
        target: '搜索引擎系统'
    }, {
        source: 'Web服务交互方案',
        target: 'RPC'
    }, {
        source: 'Web服务交互方案',
        target: 'RESTFul'
    }, {
        source: 'RPC',
        target: 'XML-RPC'
    }, {
        source: 'RPC',
        target: 'SOAP'
    }, {
        source: 'RPC',
        target: 'JSON-RPC'
    }, {
        source: 'RPC',
        target: 'CORBA'
    }, {
        source: 'RPC',
        target: 'Java RMI'
    }, {
        source: 'RPC',
        target: 'REST-RPC'
    }, {
        source: 'RPC',
        target: 'Java RMI'
    }, {
        source: 'SOA',
        target: 'Web服务交互方案'
    }, {
        source: '数据湖',
        target: '数据沙箱'
    }, {
        source: '数据湖',
        target: 'Hadoop'
    }, {
        source: '数据存储技术',
        target: '数据湖'
    }, {
        source: '数据存储技术',
        target: '数据仓库'
    }, {
        source: 'Java',
        target: 'Java RMI'
    }
];