var nodes = [
    {
        name: 'Java'
    }, {
        name: 'TiDB'
    }, {
        name: '数据中台'
    }, {
        name: '数据中台用户'
    }, {
        name: '数据用户'
    }, {
        name: '数据消费者'
    }, {
        name: '业务系统'
    }, {
        name: '数据中台产品'
    }, {
        name: 'Data API'
    }, {
        name: '数据服务'
    }, {
        name: '商业智能'
    }, {
        name : '数据仓库'
    }, {
        name: '技术类系统'
    }, {
        name: '业务'
    }, {
        name: '决策层'
    }, {
        name: '分析报表'
    }, {
        name: '数据湖'
    }, {
        name: '数据平台'
    }, {
        name: '提供服务的方法'
    }, {
        name: '使用对象'
    }, {
        name: '数据开发者'
    }, {
        name: '数据技术人员'
    }, {
        name: '数据分析师'
    }, {
        name: '商业智能产出物'
    }, {
        name: '数据集'
    }, {
        name: 'Data Set'
    }, {
        name: 'Database as a Service'
    }, {
        name: 'Data Market'
    }, {
        name: '阿里中台'
    }, {
        name: 'One Data'
    }, {
        name: 'One Entity'
    }, {
        name: 'One Service'
    }, {
        name: 'RTP'
    }, {
        name: 'oRTP',
        url: 'http://www.linphone.org/technical-corner/ortp/overview'
    }, {
        name: 'JRTP'
    }, {
        name: 'OLAP'
    }, {
        name: 'OLTP'
    }, {
        name: '数据处理类型'
    }, {
        name: 'WebGL'
    }, {
        name: 'JavaScript'
    }, {
        name: 'OpenGL'
    }, {
        name: 'HTML5'
    }, {
        name: 'DDD'
    }, {
        name: 'Axon'
    }, {
        name: 'ROLAP'
    }, {
        name: 'MOLAP'
    }, {
        name: 'HOLAP'
    }, {
        name: 'mondrian'
    }, {
        name: 'Presto'
    }, {
        name: 'facebook'
    }, {
        name: 'DRDS'
    }, {
        name: '阿里'
    }, {
        name: 'Kylin'
    }, {
        name: 'Lylin'
    }, {
        name: 'pinot'
    }, {
        name: 'Druid'
    }, {
        name: 'apache'
    }, {
        name: 'ebay'
    }, {
        name: 'linkedin'
    }, {
        name: 'MPP'
    }, {
        name: 'Impala'
    }, {
        name: 'SparkSQL'
    }, {
        name: 'Drill'
    }, {
        name: '预计算系统'
    }, {
        name: '搜索引擎系统'
    }, {
        name: 'Elasticsearch'
    }, {
        name: 'OLAP引擎'
    }, {
        name: 'Web服务交互方案'
    }, {
        name: 'SOAP'
    }, {
        name: 'XML-RPC'
    }, {
        name: 'RPC'
    }, {
        name: 'RESTful'
    }, {
        name: 'JSON-RPC',
        url: 'https://www.jsonrpc.org/specification_v1'
    }, {
        name: 'REST-RPC'
    }, {
        name: 'SOA'
    }, {
        name: 'SSAS'
    }, {
        name: '数据沙箱'
    }, {
        name: 'Hadoop'
    }, {
        name: '数据存储技术'
    }, {
        name: 'Java RMI'
    }, {
        name: 'Flink'
    }, {
        name: 'HiBench'
    }, {
        name: 'Benchmark'
    }, {
        name: 'HiBench Support'
    }, {
        name: 'Spark'
    }, {
        name: 'streaming workloads'
    }, {
        name: 'Spark Streaming'
    }, {
        name: 'Storm'
    }, {
        name: 'Gearpump'
    }, {
        name: 'JSON-WSP'
    }, {
        name: 'gRPC'
    }, {
        name: 'REST'
    }, {
        name: 'Web Service'
    }, {
        name: 'Ajax'
    }, {
        name: 'JSON'
    }, {
        name: '请求响应协议'
    }
];